ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - before: if [[ -z "$experiment" ]]; then cd frontend; else cd playground/$experiment; fi
    command: nvm install 13.3.0 && npm install && npm start